<?php

declare(strict_types = 1);

use Centrex\Inventory\Models\{Customer, Supplier};
use Centrex\Inventory\Support\InventoryEntityRegistry;

it('auto-generates a customer code when left blank on create', function (): void {
    $payload = InventoryEntityRegistry::fillablePayload('customers', ['name' => 'Acme Corp'], forCreate: true);

    expect($payload['code'])->toBe('CUS-00001');
});

it('auto-generates a supplier code when left blank on create', function (): void {
    $payload = InventoryEntityRegistry::fillablePayload('suppliers', ['name' => 'Supplier Ltd'], forCreate: true);

    expect($payload['code'])->toBe('SUP-00001');
});

it('keeps a manually entered code', function (): void {
    $payload = InventoryEntityRegistry::fillablePayload('customers', ['name' => 'Acme', 'code' => 'MY-CODE'], forCreate: true);

    expect($payload['code'])->toBe('MY-CODE');
});

it('does not generate a code on update payloads', function (): void {
    $payload = InventoryEntityRegistry::fillablePayload('customers', ['name' => 'Acme']);

    expect($payload['code'])->toBeNull();
});

it('skips codes that are already taken', function (): void {
    Customer::create(['code' => 'CUS-00002', 'name' => 'Existing A', 'currency' => 'BDT']);

    // next id would be 2 → CUS-00002 is taken → falls through to CUS-00003
    expect(InventoryEntityRegistry::autoGeneratedCode('customers'))->toBe('CUS-00003');
});

it('increments from the highest id', function (): void {
    Supplier::create(['code' => 'S-1', 'name' => 'One', 'currency' => 'BDT']);
    Supplier::create(['code' => 'S-2', 'name' => 'Two', 'currency' => 'BDT']);

    expect(InventoryEntityRegistry::autoGeneratedCode('suppliers'))->toBe('SUP-00003');
});

it('returns null for entities without code generation', function (): void {
    expect(InventoryEntityRegistry::autoGeneratedCode('warehouses'))->toBeNull();
});
